# wrangler.toml

name = "instituto-lael-platform"
compatibility_date = "2024-01-01"

# Configuración de la Base de Datos D1
[[d1_databases]]
binding = "DB" # Así la llamaremos en el código: env.DB
database_name = "lael-db" # El nombre que le diste en Cloudflare
database_id = "c3a83b23-7dcb-4dfb-b1c5-27e0bda4458e" # Tu ID real